name: Java, Gradle and Custom JRE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 21 using Microsoft distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Grant execute permission for Gradle wrapper and build
      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      # Set up Docker Buildx for Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker (if necessary)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image using Docker action
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Not pushing to Docker Hub
          tags: jayesh2026/helloworld:latest

      # Start services using Docker Compose
      - name: Start Docker Compose
        uses: docker/compose-action@v3
        with:
          up: helloworld  # Service name defined in docker-compose.yml

      # Wait for the application to start and check health
      - name: Wait for application to start
        run: |
          sleep 30
          curl --fail http://localhost:8081/hello || exit 1
