name: Java, Gradle and Custom JRE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 21 using Microsoft distribution
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Grant execute permission for Gradle wrapper and build
      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build Docker image
      - name: Build Docker image
        run: docker-compose build

      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d

      # Wait for the application to start and check health
      - name: Wait for application to start
        run: |
          sleep 30
          curl --fail http://localhost:8081/hello || exit 1
